#!/usr/bin/env bash
set -euo pipefail

cat > "$1"/.editorconfig << "EOF"
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[{Makefile,go.mod,go.sum,*.go}]
indent_style = tab

[*.md]
indent_size = 4
trim_trailing_whitespace = false

[Dockerfile]
indent_size = 4
EOF
