#!/usr/bin/env bash

current_userid=$(id -u)

if [ "$current_userid" -ne 0 ]; then
    echo "$(basename "$0") uninstallation script requires superuser privileges to run" >&2
    exit 1
fi

echo "This script will delete these files/directories permanently:"
echo "/usr/local/go"
echo "/etc/paths.d/go"
echo ""

read -p -r "Are you sure you want to proceed? [Y/n] " input

if [[ $input =~ ^[Yy]$ ]]; then
  rm -rf /usr/local/go
  rm /etc/paths.d/go
  echo "Golang was successfully removed from the system."
else
    echo "Aborting..."
fi
